steps:
  # Step 1: Build Docker Image with Firebase Variables
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/accordlinux-simulation-parody/accord:$COMMIT_SHA'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_API_KEY=$_REACT_APP_FIREBASE_API_KEY'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=$_REACT_APP_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_PROJECT_ID=$_REACT_APP_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=$_REACT_APP_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$_REACT_APP_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_APP_ID=$_REACT_APP_FIREBASE_APP_ID'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID=$_REACT_APP_FIREBASE_MEASUREMENT_ID'
      - '.'

  # Step 2: Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/accordlinux-simulation-parody/accord:$COMMIT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'accord'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/accordlinux-simulation-parody/accord:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
