steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/accord'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_API_KEY=$_REACT_APP_FIREBASE_API_KEY'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=$_REACT_APP_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_PROJECT_ID=$_REACT_APP_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=$_REACT_APP_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$_REACT_APP_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_APP_ID=$_REACT_APP_FIREBASE_APP_ID'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID=$_REACT_APP_FIREBASE_MEASUREMENT_ID'
      - '.'